<?php

declare(strict_types=1);
require_once __DIR__.'/../../includes/cors.php';require_once __DIR__.'/../../includes/response.php';require_once __DIR__.'/../../includes/helpers.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/admin-audit.php';require_once __DIR__.'/../../includes/admin-access.php';require_once __DIR__.'/../../includes/security-events.php';
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(['success'=>false,'message'=>'Method not allowed'],405);$actor=require_auth($pdo);require_role($actor,['super_admin']);$in=get_json_input();require_sensitive_confirmation($pdo,$actor,$in);$action=(string)($in['action']??'');$userId=(int)($in['user_id']??$actor['id']);if($userId<=0)json_response(['success'=>false,'message'=>'مدیر نامعتبر است.'],422);
try{$pdo->beginTransaction();$target=$pdo->prepare("SELECT id,name,ip_allowlist_enabled FROM users WHERE id=:id AND role='super_admin' LIMIT 1 FOR UPDATE");$target->execute([':id'=>$userId]);$admin=$target->fetch();if(!$admin)throw new ApiPublicException('مدیر پیدا نشد.');
if($action==='save'){$id=(int)($in['id']??0);$label=trim((string)($in['label']??''));$cidr=security_normalize_cidr((string)($in['ip_cidr']??''));$active=!isset($in['is_active'])||!empty($in['is_active'])?1:0;if($label===''||!$cidr)throw new ApiPublicException('عنوان و IP/CIDR معتبر وارد کنید.');if($id>0){$q=$pdo->prepare('UPDATE admin_ip_allowlist SET label=:label,ip_cidr=:cidr,is_active=:active,updated_at=NOW() WHERE id=:id AND user_id=:user_id');$q->execute([':label'=>$label,':cidr'=>$cidr,':active'=>$active,':id'=>$id,':user_id'=>$userId]);}else{$q=$pdo->prepare('INSERT INTO admin_ip_allowlist(user_id,label,ip_cidr,is_active,created_by,created_at) VALUES(:user_id,:label,:cidr,:active,:created_by,NOW())');$q->execute([':user_id'=>$userId,':label'=>$label,':cidr'=>$cidr,':active'=>$active,':created_by'=>$actor['id']]);$id=(int)$pdo->lastInsertId();}admin_audit_log($pdo,$actor,'security.ip_rule_saved','ip_allowlist',$id,'قانون IP مدیر ذخیره شد',null,['user_id'=>$userId,'label'=>$label,'ip_cidr'=>$cidr,'is_active'=>(bool)$active],['target_user_id'=>$userId]);}
elseif($action==='delete'){$id=(int)($in['id']??0);$pdo->prepare('DELETE FROM admin_ip_allowlist WHERE id=:id AND user_id=:user_id')->execute([':id'=>$id,':user_id'=>$userId]);admin_audit_log($pdo,$actor,'security.ip_rule_deleted','ip_allowlist',$id,'قانون IP مدیر حذف شد',null,['user_id'=>$userId],['target_user_id'=>$userId]);}
elseif($action==='set_enabled'){$enabled=!empty($in['enabled']);if($enabled){$count=$pdo->prepare('SELECT COUNT(*) FROM admin_ip_allowlist WHERE user_id=:user_id AND is_active=1');$count->execute([':user_id'=>$userId]);if((int)$count->fetchColumn()<1)throw new ApiPublicException('برای فعال‌سازی محدودیت IP حداقل یک قانون فعال لازم است.');if($userId===(int)$actor['id']&&!security_admin_ip_allowed($pdo,$userId,auth_client_ip()??''))throw new ApiPublicException('IP فعلی شما در قوانین فعال نیست و فعال‌سازی باعث قفل‌شدن حساب می‌شود.');}$pdo->prepare('UPDATE users SET ip_allowlist_enabled=:enabled,token_version=token_version+1 WHERE id=:id')->execute([':enabled'=>$enabled?1:0,':id'=>$userId]);auth_revoke_sessions($pdo,$userId,(int)$actor['id'],'IP allowlist setting changed');admin_audit_log($pdo,$actor,'security.ip_allowlist_toggled','admin_user',$userId,'محدودیت IP مدیر تغییر کرد',['enabled'=>(bool)$admin['ip_allowlist_enabled']],['enabled'=>$enabled],['target_user_id'=>$userId]);}
else throw new ApiPublicException('عملیات نامعتبر است.');$pdo->commit();json_response(['success'=>true,'message'=>'تنظیمات IP ذخیره شد.']);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();json_response(['success'=>false,'message'=>safe_api_exception_message($e,'ذخیره تنظیمات IP ناموفق بود.')],422);}
