<?php
require_once __DIR__.'/../../includes/cors.php';require_once __DIR__.'/../../includes/response.php';require_once __DIR__.'/../../includes/helpers.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/subscription.php';require_once __DIR__.'/../../includes/admin-audit.php';
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(['success'=>false,'message'=>'Method not allowed'],405);$user=require_auth($pdo);require_role($user,['super_admin']);$in=get_json_input();
$tenant=(int)($in['tenant_id']??0);$plan=(int)($in['plan_id']??0);$status=(string)($in['status']??'active');$cycle=(string)($in['billing_cycle']??'manual');$currency=strtoupper(trim((string)($in['currency']??'IRR')));$price=(float)($in['price']??0);
if(!$tenant||!$plan||!in_array($status,['trial','active','past_due','suspended'],true)||!in_array($cycle,['monthly','quarterly','yearly','manual'],true)||!preg_match('/^[A-Z]{3}$/',$currency)||$price<0)json_response(['success'=>false,'message'=>'Invalid subscription data'],422);
try{$start=new DateTimeImmutable((string)($in['starts_at']??'now'));$end=new DateTimeImmutable((string)($in['ends_at']??''));}catch(Throwable $e){json_response(['success'=>false,'message'=>'Invalid date'],422);}if($end<=$start)json_response(['success'=>false,'message'=>'ends_at must be after starts_at'],422);
try{$pdo->beginTransaction();$check=$pdo->prepare('SELECT id FROM tenants WHERE id=:t FOR UPDATE');$check->execute([':t'=>$tenant]);if(!$check->fetch())throw new RuntimeException('Customer not found');$check=$pdo->prepare('SELECT id FROM plans WHERE id=:p AND is_active=1');$check->execute([':p'=>$plan]);if(!$check->fetch())throw new RuntimeException('Active plan not found');
$pdo->prepare("UPDATE tenant_subscriptions SET status='cancelled',updated_at=NOW() WHERE tenant_id=:t AND status IN ('trial','active','past_due','suspended')")->execute([':t'=>$tenant]);
$q=$pdo->prepare("INSERT INTO tenant_subscriptions(tenant_id,plan_id,status,billing_cycle,starts_at,ends_at,trial_ends_at,auto_renew,price,currency,created_by) VALUES(:t,:p,:s,:c,:sa,:ea,:trial,:renew,:price,:currency,:by)");$q->execute([':t'=>$tenant,':p'=>$plan,':s'=>$status,':c'=>$cycle,':sa'=>$start->format('Y-m-d H:i:s'),':ea'=>$end->format('Y-m-d H:i:s'),':trial'=>!empty($in['trial_ends_at'])?(new DateTimeImmutable($in['trial_ends_at']))->format('Y-m-d H:i:s'):null,':renew'=>!empty($in['auto_renew'])?1:0,':price'=>$price,':currency'=>$currency,':by'=>$user['id']]);$id=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE tenants SET plan_id=:p WHERE id=:t')->execute([':p'=>$plan,':t'=>$tenant]);admin_audit_log($pdo,$user,'subscription.created','subscription',$id,'Subscription created',null,['tenant_id'=>$tenant,'plan_id'=>$plan,'status'=>$status],['tenant_id'=>$tenant,'plan_id'=>$plan]);$pdo->commit();json_response(['success'=>true,'message'=>'Subscription created','subscription_id'=>$id],201);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();json_response(['success'=>false,'message'=>$e->getMessage()],422);}

