"use client";
import {useEffect,useState} from "react";import {useParams,useRouter} from "next/navigation";import AppShell from "@/components/layout/AppShell";import {apiRequest,getAuthUser} from "@/lib/api";
type Data={subscription:any;payments:any[];history:any[]};
export default function SubscriptionDetail(){const {id}=useParams<{id:string}>();const router=useRouter();const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [end,setEnd]=useState("");const [amount,setAmount]=useState("");const [reference,setReference]=useState("");
async function load(){try{setData(await apiRequest(`/super-admin/subscription-show.php?id=${id}`))}catch(e){setError(e instanceof Error?e.message:"خطا")}}useEffect(()=>{const u=getAuthUser();if(!u||u.role!=="super_admin"){router.push("/dashboard");return}load()},[id,router]);
async function post(path:string,body:any){setBusy(true);setError("");try{await apiRequest(path,{method:"POST",body:JSON.stringify(body)});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
if(!data)return <AppShell title="جزئیات اشتراک"><p>{error||"در حال بارگذاری..."}</p></AppShell>;const s=data.subscription;
return <AppShell title={`اشتراک ${s.tenant_name}`} kicker="Subscription detail" description={`${s.plan_name} • ${s.status}`}><div className="sa-subscriptions detail">{error&&<div className="error">{error}</div>}<section className="subscription-detail-grid"><article className="subscription-panel"><h2>اطلاعات اشتراک</h2><dl><dt>وضعیت</dt><dd>{s.status}</dd><dt>شروع</dt><dd>{s.starts_at}</dd><dt>پایان</dt><dd>{s.ends_at}</dd><dt>روز باقی‌مانده</dt><dd>{s.days_remaining}</dd><dt>دوره</dt><dd>{s.billing_cycle}</dd><dt>مبلغ</dt><dd>{Number(s.price).toLocaleString("fa-IR")} {s.currency}</dd></dl><div className="subscription-actions">{["active","past_due","suspended","cancelled"].map(x=><button disabled={busy} className="btn secondary" key={x} onClick={()=>post("/super-admin/subscription-status-update.php",{subscription_id:s.id,status:x})}>{x}</button>)}</div></article><article className="subscription-panel"><h2>تمدید</h2><label>تاریخ پایان جدید<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><button disabled={busy||!end} className="btn primary" onClick={()=>post("/super-admin/subscription-renew.php",{subscription_id:s.id,ends_at:end})}>ثبت تمدید</button><hr/><h2>ثبت پرداخت دستی</h2><label>مبلغ<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>شماره پیگیری<input value={reference} onChange={e=>setReference(e.target.value)}/></label><button disabled={busy||amount===""} className="btn primary" onClick={()=>post("/super-admin/subscription-payment-create.php",{subscription_id:s.id,amount:Number(amount),currency:s.currency,status:"paid",payment_method:"manual",reference_number:reference})}>ثبت پرداخت</button></article></section><section className="subscription-panel"><h2>پرداخت‌ها</h2><table className="subscription-table"><thead><tr><th>تاریخ</th><th>مبلغ</th><th>وضعیت</th><th>روش</th><th>پیگیری</th></tr></thead><tbody>{data.payments.map(p=><tr key={p.id}><td>{p.paid_at||p.created_at}</td><td>{Number(p.amount).toLocaleString("fa-IR")} {p.currency}</td><td>{p.status}</td><td>{p.payment_method}</td><td>{p.reference_number||"—"}</td></tr>)}</tbody></table></section><section className="subscription-panel"><h2>تاریخچه پلن و اشتراک</h2>{data.history.map(h=><div className="subscription-history" key={h.id}><strong>{h.plan_name}</strong><span>{h.status}</span><span>{h.starts_at} تا {h.ends_at}</span></div>)}</section></div></AppShell>}

